export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

//Persist
export const REHYDRATE = 'REHYDRATE';

//Group
export const SET_GROUP_NAME = 'SET_GROUP_NAME';
export const ADD_GROUP_COINS = 'ADD_GROUP_COINS';
export const REMOVE_GROUP_COINS = 'REMOVE_GROUP_COINS';
export const SET_GROUP_IMAGE = 'SET_GROUP_IMAGE';
export const SET_PICKER = 'SET_PICKER';
export const DELETE_GROUP = 'DELETE_GROUP';

//Modal
export const TOGGLE_VISIBILITY = 'TOGGLE_VISIBILITY';
export const ENABLE_VISIBILITY = 'ENABLE_VISIBILITY';
export const DISABLE_VISIBILITY = 'DISABLE_VISIBILITY';

//Questions
export const SET_GROUP_ROUTE = 'SET_GROUP_ROUTE';
export const SET_GROUP_GRADE = 'SET_GROUP_GRADE';
export const FETCH_QUESTIONS_SUCCESS = 'FETCH_QUESTIONS_SUCCESS';
export const FETCH_QUESTIONS_FAILURE = 'FETCH_QUESTIONS_FAILURE';
export const GET_QUESTION = 'GET_QUESTION';
export const GET_QUESTIONS = 'GET_QUESTIONS';
export const INIT_ANSWERS = 'INIT_ANSWERS';
export const TOGGLE_ANSWER = 'TOGGLE_ANSWER';
export const SET_ANSWER = 'SET_ANSWER';
export const REDUCE_REWARD = 'REDUCE_REWARD';
export const COMPLETED_QUESTION = 'COMPLETED_QUESTION';
export const DELETE_QUESTIONS = 'DELETE_QUESTIONS';

//Scores
export const FETCH_SCORES_SUCCESS = 'FETCH_SCORES_SUCCESS';
export const FETCH_SCORES_FAILURE = 'FETCH_SCORES_FAILURE';
export const SAVE_SCORE_SUCCESS = 'SAVE_SCORE_SUCCESS';
export const SAVE_SCORE_FAILURE = 'SAVE_SCORE_FAILURE';